language: generic
matrix:
  include:
  - os: linux
    dist: xenial
    sudo: required
    language: cpp
    compiler: gcc
    addons:
      apt:
        sources:
          - ubuntu-toolchain-r-test
        packages:
          - g++-8
          - libatlas-base-dev
          - libblas-dev
  - os: osx
    osx_image: xcode10.2
    language: c++
    compiler: clang
before_install:
- |
  python3 -m pip install pip --upgrade
  which cmake &> /dev/null || python3 -m pip install cmake --upgrade --user
  if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then
    sudo ln -fs /usr/bin/gcc-8 /usr/local/bin/gcc
    sudo ln -fs /usr/bin/g++-8 /usr/local/bin/g++
    gcc -v
  fi
script:
- |
  source mkn.sh
  git clone https://github.com/Dekken/maiken -b master --depth 1 maiken
  [[ "${TRAVIS_OS_NAME}" == "osx" ]]   && make bsd -C maiken CXX=clang++
  [[ "${TRAVIS_OS_NAME}" == "linux" ]] && make nix -C maiken
  mv maiken/mkn .
  export KUL_GIT_CO="--depth 3"
  export MKN_LIB_LINK_LIB=1
  ./mkn build -p test -Oa "-std=c++17 -fPIC" run
