version: 0.1.{build}
max_jobs: 1
image:
- Visual Studio 2017
init:
  - git config --global core.autocrlf input
clone_depth: 1
hosts:
  queue-server: 127.0.0.1
  db.server.com: 127.0.0.2
platform: x64
configuration: Release
cache:
  - C:\ProgramData\chocolatey\bin -> appveyor.yml
  - C:\ProgramData\chocolatey\lib -> appveyor.yml
build_script:
- |
  CALL "C:\Program Files (x86)\Microsoft Visual Studio\2017\Community\VC\Auxiliary\Build\vcvars64.bat"
  SET PATH=%PWD%;C:\Python36-x64;C:\Python36-x64\Scripts;C:\Program Files\Git\usr\bin;%PATH%
  C:\Python36-x64\python -m pip install pip --upgrade
  C:\Python36-x64\python -m pip install cmake --upgrade --user
  CALL mkn.bat
  curl -o mkn.exe -L https://github.com/Dekken/maiken/raw/binaries/win10_x64/mkn.exe
  SET MKN_CL_PREFERRED=1
  SET KLOG=3
  mkn build -SOa "-DGSL_DLL -EHsc" -p test run
